# Generated by Django 3.2.7 on 2021-09-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextCategoryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('is_gold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_gold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='text_app.textcategorymodel')),
            ],
        ),
    ]
